### ISSUE TITLE
Uncaught reference error: PhoneGap is not defined at :1

### ISSUE THREAD

**Issue by AaronMT** [mozilla/soup#3]
D/PhoneGapLog( 4573): : Line 1 : Uncaught ReferenceError: PhoneGap is not defined
E/Web Console( 4573): Uncaught ReferenceError: PhoneGap is not defined at :1

I get the following two harmless errors thrown in my log when I attempt to use my devices menu and search buttons while visiting (post chrome-less window launch) one of the hardcoded open web apps

**Comment by serjant** [comment]
Btw I get the same error while navigating from the my phonegap application google maps, for example to reproduce:

window.location.href = 'http://maps.google.com/maps?&saddr=13.042206,80.17000&daddr=9.580000,78.100000';

Then the menu and back buttons do not work and the mentioned above exception is thrown

**Comment by AaronMT** [comment]
Dead project.
